// ============================================================
//  HYDROCLIMATE LAB — EDIT ALL YOUR CONTENT HERE
//  Change text/links below and push to GitHub to update site.
// ============================================================

const LAB_DATA = {

  lab: {
    name: "HydroClimate Lab",
    institute: "IIT Kharagpur",
    department: "Agricultural & Food Engineering Department",
    tagline: "Understanding the science of monsoon, moisture transport, hydroclimate extremes across South Asia and Study the Crop Behaviour",
    established: "IIT Kharagpur",
    logo_initials: "HL",
  },

  pi: {
    name: "Prof. Amey Pathak",
    short_name: "Prof. Pathak",
    title: "Assistant Professor, Agricultural & Food Engineering Department",
    photo: "images/Professor.png",
    email: "amey[at]agfe[dot]iitkgp[dot]ac[dot]in",
    phone: "+91-3222-283XXX",
    office: "Room No.:FP206, Agricultural & Food Engineering Dept., IIT Kharagpur — 721302, West Bengal, India",
    degree: "Ph.D., IIT Bombay (2017) · M.Tech, IIT Bombay (2010) · B.Tech, MPKV Rahuri (2008)",
    bio: `Prof. Amey Pathak is an Assistant Professor in the Department of Agricultural & Food Engineering at IIT Kharagpur. His research sits at the intersection of <strong>hydroclimatology, monsoon dynamics, and land-atmosphere interactions</strong>, with a focus on South Asia's complex water-climate system.<br/><br/>
    He completed his Ph.D. from IIT Bombay where he pioneered the use of <strong>Dynamic Recycling Models</strong> to quantify precipitation recycling during the Indian Summer Monsoon. His work has been cited over <strong>2,000 times</strong> and published in leading journals including <em>Nature Climate Change</em>, <em>Nature Communications</em>, <em>Journal of Hydrometeorology</em>, and <em>Geophysical Research Letters</em>.<br/><br/>
    Prof. Pathak leads the <strong>Hydroclimate Laboratory</strong> at IIT KGP where his team investigates moisture transport, extreme rainfall, atmospheric rivers, drought assessment, and AI/ML applications in climate and agriculture.`,
    google_scholar: "https://scholar.google.com/citations?user=do9u7u8AAAAJ&hl=en",
    researchgate: "https://www.researchgate.net/profile/Amey-Pathak",
    orcid: "https://orcid.org/",
    cv_link: "images/cv.pdf",
    iitpage: "https://www.iitkgp.ac.in/department/AG/faculty/ag-amey",
  },

  stats: [
    { number: "2000+", label: "Citations" },
    { number: "25+",   label: "Publications" },
    { number: "3+",    label: "Research Scholars" },
    { number: "15+",   label: "Years of Research" },
    { number: "2+",    label: "Funded Projects" },
  ],

  research: [
    {
      icon: "🌧",
      color: "#e8f4fb",
      title: "Precipitation Recycling & Moisture Transport",
      desc: "Quantifying the role of evapotranspiration and land surface processes in generating monsoon precipitation using Dynamic Recycling Models and Lagrangian moisture tracking. Identifying oceanic and terrestrial moisture sources feeding Indian Summer Monsoon extremes.",
      tag: "Core Research",
    },
    {
      icon: "🌊",
      color: "#e1f5ee",
      title: "Atmospheric Rivers & Extreme Rainfall",
      desc: "Detection and characterization of atmospheric rivers linked to extreme precipitation events across the Indian subcontinent, especially in the core monsoon zone and Western Himalayas. Event-based 3D Lagrangian moisture tracking.",
      tag: "Ongoing",
    },
    {
      icon: "☀️",
      color: "#faeeda",
      title: "Drought Monitoring & Remote Sensing",
      desc: "Multi-index drought assessment using satellite remote sensing (MODIS, GRACE, GPM) across India.",
      tag: "Active",
    },
    {
      icon: "🌍",
      color: "#f0f4ff",
      title: "Land-Atmosphere Interactions",
      desc: "Investigating feedbacks between land use/land cover change and Indian Summer Monsoon rainfall. Using WRF regional climate model to quantify urbanization and irrigation impacts on monsoon intensity and distribution.",
      tag: "Active",
    },
    {
      icon: "🤖",
      color: "#eaf3de",
      title: "AI/ML in Climate & Agriculture",
      desc: "Application of machine learning, deep learning, and geoinformatics for climate prediction, crop water stress detection (spectral reflectance studies), and agro-informatics.",
      tag: "Growing",
    },
    {
      icon: "🌱",
      color: "#faece7",
      title: "Crop Monitoring & System Development",
      desc: "Studying Crop behaviour and capture the response to model it.",
      tag: "Growing",
    },
  ],

  team: [
    {
      id: "amey-pathak",
      name: "Prof. Amey Pathak",
      role: "Faculty",
      category: "Faculty",
      research: "Hydroclimatology, Land Atmosphere Interaction, Monsoon Dynamics, Moisture Recycling, Digital Agriculture",
      photo: "images/Professor.png",
      initials: "AP",
      color: "#1a4a8a",
      email: "amey[at]agfe[dot]iitkgp[dot]ac[dot]in",
      phone: "+91-3222-283XXX",
      joining_year: "2018",
      hometown: "M.P., Maharashtra, India",
      education: [
        "Ph.D., Civil Engineering, IIT Bombay (2017), India",
        "M.Tech, Natural Resources Engineering, IIT Bombay (2010), India",
        "B.Tech, Agricultural Engineering, Mahatma Phule Krishi Vidyapeeth, Rahuri (2008)",
      ],
      bio: "Prof. Amey Pathak is an Assistant Professor in the Department of Agricultural & Food Engineering at IIT Kharagpur. His research focuses on hydroclimatology, monsoon dynamics, land-atmosphere interactions and Digital agriculture to transform knowledge into the digital world. He has over 2,000 citations and has published in Nature Communications, Journal of Hydrometeorology, Journal of Climate, and other leading journals.",
      interests: ["Moisture Recycling", "Hydroclimatology", "Monsoon Dynamics", "Land Atmosphere Interaction", "Digital Agriculture", "Remote Sensing and GIS"],
      publications: [],
      google_scholar: "https://scholar.google.com/citations?user=do9u7u8AAAAJ&hl=en",
      researchgate: "https://www.researchgate.net/profile/Amey-Pathak",
      linkedin: "https://www.linkedin.com/in/amey-pathak-95128716/",
      website: "https://www.iitkgp.ac.in/department/AG/faculty/ag-amey",
    },
    {
      id: "ranjan-kumar",
      name: "Ranjan Kumar",
      role: "Research Scholar",
      category: "Research Scholar",
      research: "Precipitation Recycling,  Atmospheric Moisture Transport, Indian Summer Monsoon Rainfall",
      photo: "images/Ranjan.png",
      initials: "RK",
      color: "#3a3a8b",
      email: "",
      phone: "",
      joining_year: "2020",
      hometown: "Bihar, India",
      education: [
        "PhD (ongoing), IIT Kharagpur, India (2020--)",
        "M.Tech, Anand Agricultural University, Gujarat, India (2019)", 
        "B.Tech, Agricultural Engineering,  Kerala Agricultural University, India (2017)",
      ],
      bio: "Ranjan Kumar is working in the areas of atmospheric moisture transport, precipitation recycling, and extreme rainfall dynamics associated with the Indian Summer Monsoon. His research focuses on understanding moisture pathways, land–atmosphere interactions, hydroclimatic extremes, and sustainable water resource systems using geospatial analysis, remote sensing, and environmental modelling. Ranjan's research focuses on the atmospheric moisture budget during ENSO years and its relationship to Indian Summer Monsoon rainfall variability. He uses reanalysis datasets and diagnostic tools to study evaporation-precipitation balance during contrasting climate years.",
      interests: ["Precipitation Recycling", "Atmospheric Moisture Transport", "Monsoon Variability", "Reanalysis Data", "Indian Summer Monsoon Rainfall"],
      publications: [
        {
      "authors": "Ranjan Kumar, Amey Pathak, Shashikanth Kulkarni",
      "title": "Climatic and transient controls on Indian monsoon E-P variability using moisture-budget decomposition",
      "publication": "Environmental Research Communications",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2026",
      "publisher": "IOP Science",
      "type": "Journal",
      "doi": "https://iopscience.iop.org/article/10.1088/2515-7620/ae73ee/meta"},
         {
      "authors": "Ranjan Kumar, Amey Pathak",
      "title": "Lagrangian quantification of atmospheric moisture sources for extreme rainfall events over India during the 2023 summer monsoon",
      "publication": "Science of the Total Environment https://doi.org/10.1016/j.scitotenv.2025.180389",
      "volume": "1000",
      "number": "",
      "pages": "180389",
      "year": "2025",
      "publisher": "Elsevier, https://doi.org/10.1016/j.scitotenv.2025.180389",
      "type": "Journal",
      "doi": "https://doi.org/10.1016/j.scitotenv.2025.180389"},
      
      ],
      google_scholar: "https://scholar.google.com/citations?user=JwmdFqMAAAAJ&hl=en",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/ranjan-kumar-0527601b1/?skipRedirect=true",
      website: "",
    },
    {
      id: "ranjeet-bais",
      name: "Ranjeet S. Bais",
      role: "Research Scholar",
      category: "Research Scholar",
      research: "S2S Prediction, Reliability Indices",
      photo: "images/Ranjeet.jpg",
      initials: "RB",
      color: "#0f7b8c",
      email: "",
      phone: "",
      joining_year: "2020",
      hometown: "Madhya Pradesh, India",
      education: [
        "Ph.D. (ongoing), IIT Kharagpur, India (2020--)",
        "M.Tech,  IIT Kharagpur, India (2020)",
        "B.Tech, Agricultural Engineering, Tamil Nadu Agricultural University, India (2018)",
      ],
      bio: "Ranjeet is working on Seasonal-to-Subseasonal (S2S) weather prediction reliability indices for societal applications. His work focuses on improving the usability of S2S model forecasts for agriculture and disaster management.",
      interests: ["S2S Prediction", "Monsoon Forecasting", "Reliability Indices", "Climate Services"],
      publications: [
        {
      "authors": "Ranjeet Singh Bais, Amey Pathak",
      "title": "Extreme learning machine based sub-seasonal forecasting of Indian Monsoon rainfall over core monsoon zone",
      "publication": "Theoretical and Applied Climatology",
      "volume": "157",
      "number": "325",
      "pages": "325",
      "year": "2026",
      "publisher": "Springer Nature; https://doi.org/10.1007/s00704-026-06274-z",
      "type": "Journal",
      "doi": "https://doi.org/10.1007/s00704-026-06274-z"
    },

        
      ],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/ranjeet-singh-bais-a7582b180/",
      website: "",
    },
    {
      id: "Alok-k",
      name: "Alok Kumar Maurya",
      role: "Research Scholar",
      category: "Research Scholar",
      research: "Digital Agriculture, RS and GIS, IoTs and AI application in Agriculture",
      photo: "images/Alok.jpg",
      initials: "AK",
      color: "#1d6d3a",
      email: "akmaurya.iitkgp@gmail.com",
      phone: "",
      joining_year: "2021",
      hometown: "UP, India",
      education: [
        "Ph.D. (ongoing), IIT Kharagpur, India (2021--)",
        "M.Tech, IIT Kharagpur, India (2021)",
        "B.Tech, Agricultural Engineering, SHUATS Prayagraj, India (2019)",
      ],
      bio: "Alok is studying the response of crops under biotic and abiotic stress using remote sensing, AI and transforming all information in the digital world (digital agriculture).",
      interests: ["Digital Agriculture", "RS and GIS application in Agriculture", "IoTs", "AI in Agriculture"],
      publications: [
        {
      "authors": "Alok Kumar Maurya, Amey Pathak ",
      "title": "Leveraging the use of digital agriculture and machine learning for accurate prediction of Leaf Area Index (LAI)",
      "publication": "Computers and Electronics in Agriculture",
      "volume": "239",
      "number": "110947, ISSN 0168-1699",
      "pages": "",
      "year": "2025",
      "publisher": "Elsevier, https://doi.org/10.1016/j.compag.2025.110947",
      "type": "Journal",
      "doi": "https://doi.org/10.1016/j.compag.2025.110947"
    },

      ],
      google_scholar: "https://scholar.google.com/citations?user=TmQQe0sAAAAJ&hl=en",
      researchgate: "",
      linkedin: "https://www.linkedin.com/feed/",
      website: "",
    },
    {
      id: "Prasant-J",
      name: "Jarapla Prashanth",
      role: "Research Scholar",
      category: "Research Scholar",
      research: "Climate Modelling",
      photo: "images/Prashanth.jpeg",
      initials: "JP",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2026",
      hometown: "Telangana, India",
      education: [
        "Ph.D. (ongoing), IIT Kharagpur, India (2026--)",
        "M.Tech, Central Institute Of Agricultural Engineering, India (2025)",
        " B.Tech, Agricultural Engineering, Professor Jayashankar Telangana State Agricultural University, India (2018)",
      ],
      bio: "Prashanth is studying the impact of Land Surface Feedbacks in Climate Model Simulations over India.",
      interests: ["Climate Modelling", "Drones application in agriculture", "IoTs", "Robotics","Aeroponics"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/er-prashanth-pawar-jarapla-6aa687295/",
      website: "",
    },
    {
      id: "Nivedita",
      name: "Nivedita Dubey",
      role: "Alumni",
      category: "Alumni",
      research: "Climate Modelling",
      photo: "images/Nivedita.jpeg",
      initials: "NV",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2018-2020",
      hometown: "Uttar Pradesh, India",
      education: [
        "Ph.D. , IIT Bombay, India (2020-2025)",
        "M.Tech, IIT Kharagpur, India (2020)",
        " B.Tech, Agricultural Engineering, College of Technology & Engineering, Udaipur, India (2018)",
      ],
      bio: "Nivedita is currently working as Postdoctoral Researcher at Washington State University.",
      interests: ["Climate Change", "Eco-hydrology","Carbon cycle","Vegetation dynamics"],
      publications: [],
      google_scholar: "https://scholar.google.com/citations?hl=en&user=QdZUfK4AAAAJ&view_op=list_works&sortby=pubdate",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/dubeynivedita14/",
      website: "",
    },
    {
      id: "Sumit",
      name: "Sumit Vishwakarma",
      role: "Alumni",
      category: "Alumni",
      research: "Crop Monitoring",
      photo: "images/Sumit.jpg",
      initials: "SV",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2018-2020",
      hometown: "Uttar Pradesh, India",
      education: [
        "Ph.D. (Ongoing) , IIT Roorkee, India (2021--)",
        "M.Tech, IIT Kharagpur, India (2020)",
        " B.Tech, Agricultural Engineering, ",
      ],
      bio: "Sumit is currently working as a Research Scholar at WRDM Department, Indian Institute of Technology, Roorkee",
      interests: ["Remote Sensing and GIS", "Land and water resource assessment","Crop Monitoring","UAV application in Agriculture"],
      publications: [],
      google_scholar: "https://scholar.google.com/citations?hl=en&user=QdZUfK4AAAAJ&view_op=list_works&sortby=pubdate",
      researchgate: "https://www.researchgate.net/profile/Sumit-Vishwakarma-6",
      linkedin: "https://www.linkedin.com/in/sumit-vishwakarma-a82247366/",
      website: "",
    },
    {
      id: "Kshitij",
      name: "Kshitish",
      role: "Alumni",
      category: "Alumni",
      research: "Climate Modelling",
      photo: "images/kshitij.jpeg",
      initials: "KT",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2018-2020",
      hometown: "Orisaa, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2020)",
        " B.Tech, Agricultural Engineering, Odisha University of Agriculture and Technology, India (2018)",
      ],
      bio: "Kshitish is currently working as an Assistant Soil Conservation Officer",
      interests: ["Climate Change", "Soil and Water Conservation"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "",
      website: "",
    },
    {
      id: "Basavaraj",
      name: "Basavaraj Bijali",
      role: "Alumni",
      category: "Alumni",
      research: "Data Science",
      photo: "images/Basavaraj.jpeg",
      initials: "BS",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2019-2021",
      hometown: "Karnataka, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2021)",
        " B.Tech, Agricultural Engineering, University of Agricultural Science Bengaluru, India (2019)",
      ],
      bio: "Basavaraj is currently working as a Data Scientist  at TVS Credit Services Ltd.",
      interests: ["Data Science"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "",
      website: "",
    },
    {
      id: "anand-g",
      name: "Anand Gupta",
      role: "Alumni",
      category: "Alumni",
      research: "Atmospheric Rivers, Extreme Precipitation",
      photo: "images/Anand.png",
      initials: "AG",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2020-2022",
      hometown: "Uttar Pradesh, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2022)",
        "B.Tech, Agricultural Engineering, SHUATS Prayagraj, India (2020)",
      ],
      bio: "Aanand Gupta is investigating atmospheric rivers (ARs) and their role in driving extreme precipitation events across the Indian subcontinent. His recent work includes event-based Lagrangian 3D moisture tracking for monsoon extremes, identifying the Western Indian Ocean as a dominant moisture source contributing up to 55% of extreme rainfall.",
      interests: ["Atmospheric Rivers", "Extreme Rainfall", "Moisture Tracking", "Lagrangian Analysis", "Ganga Basin Hydrology"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "",
      website: "",
    },
    {
      id: "dilip-g",
      name: "Dilip Patidar",
      role: "Alumni",
      category: "Alumni",
      research: "",
      photo: "images/Dilip.jpeg",
      initials: "DP",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2020-2022",
      hometown: "Madhya Pradesh, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2022)",
        "B.Tech, Agricultural Engineering, SHUATS Prayagraj, India (2020)",
      ],
      bio: "Dilip Patidar is currently working as a Lead - Product Manager@ Mati Carbon.",
      interests: ["Wastershed management", "Climate Action", "Data Analytics"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/dilippatidar/",
      website: "",
    },
    {
      id: "Pramod-k",
      name: "Pramod Chouhan",
      role: "Alumni",
      category: "Alumni",
      research: "",
      photo: "images/Pramod.jpeg",
      initials: "PC",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2021-2023",
      hometown: "Madhya Pradesh, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2023)",
        " B.Tech,Agricultural Engineering, Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya (2020)",
      ],
      bio: "Pramod is currently working in Air India Limited as a Lead Engineer(Data Science). ",
      interests: ["Data Science","AI"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/pramod-chouhan-503965237/?skipRedirect=true",
      website: "",
    },
    {
      id: "rohit-kumar",
      name: "Rohit Rahangdale",
      role: "Alumni",
      category: "Alumni",
      research: "",
      photo: "images/Rohit.jpeg",
      initials: "RK",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2021-2023",
      hometown: "Madhya Pradesh, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2023)",
        " B.Tech,Agricultural Engineering, Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya (2020)",
      ],
      bio: "Rohit is currently working as a data scientist in Zeominds IT Solutions Pvt Ltd. ",
      interests: ["Data Science", "AI/ML"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/rohitrahangdale/",
      website: "",
    },
    {
      id: "Tanusri",
      name: "Tanusri Baidya",
      role: "Alumni",
      category: "Alumni",
      research: "",
      photo: "images/Tanushri.jpeg",
      initials: "TN",
      color: "#1d6d3a",
      email: "",
      phone: "",
      joining_year: "2021-2023",
      hometown: "Assam, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2023)",
        " B.Tech, Agricultural Engineering, ..... (2020)",
      ],
      bio: "Tanushri is currently working as a DevOps Engineer at CNH.",
      interests: ["Data Science", "AI/ML"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/tanusri-baidya-b68946217/",
      website: "",
    },
    {
      id: "megha-p",
      name: "Megha P.",
      role: "Alumni",
      category: "Alumni",
      research: "Agro-Informatics, Geospatial Analysis",
      photo: "images/Megha.jpeg",
      initials: "MP",
      color: "#a34a0f",
      email: "",
      phone: "",
      joining_year: "2022-2024",
      hometown: "Telangana, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2024)",
        "B.Tech, Agricultural Engineering, Kelappaji College of Agrl. Engineering & Technology, Tavanur (2022)",
      ],
      bio: "Megha is currently working in Vassar Labs as a Subject Matter Expert in Hydrological modelling.She has also worked in the domain of agro-informatics and geospatial data analysis. She contributed to IIT KGP's Advanced E-SDP Training Program on Agro-Informatics funded by the Ministry of MSME, and focuses on applying GIS and Python-based tools for agricultural and climate data analysis.",
      interests: ["Agro-Informatics", "RS & GIS", "Hydrological Modelling"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/megha-p-b44a4a245/",
      website: "",
    },
    {
      id: "ark-raj",
      name: "Ark Raj",
      role: "Alumni",
      category: "Alumni",
      research: "Climate Modeling, Land Surface",
      photo: "images/Ark.jpeg",
      initials: "AR",
      color: "#5a8b1a",
      email: "",
      phone: "",
      joining_year: "2022-2024",
      hometown: "Jharakhand, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2024)",
        "B.Tech, Agricultural Engineering, Birsa Agricultural University (BAU), (2022)",
      ],
      bio: "Ark is currently working in HSBC as a manager (working in the field of Climate Risk Modelling and Monitoring. He has also worked on climate modelling and land surface processes, studying how land use changes and surface energy fluxes influence regional climate patterns over the Indian subcontinent. He is also involved in the lab's agro-informatics and Python training activities.",
      interests: ["Data Science", "Climate Risk Modelling and Monitoring"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/ark-raj-84a1481b1/",
      website: "",
    },
    {
      id: "bikash",
      name: "Bikash Ranjan Behera",
      role: "Alumni",
      category: "Alumni",
      research: "Climate Modelling, RS and GIS, WRF model",
      photo: "images/Bikash.jpeg",
      initials: "BK",
      color: "#5a8b1a",
      email: "bikashranjan810@gmail.com",
      phone: "+918280017290",
      joining_year: "2023-2025",
      hometown: "Odisha, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2025)",
        "B.Tech, Agricultural Engineering, College of Agricultural Engineering and Technology, OUAT (2023)",
      ],
      bio: "Bikash is currently working in Ruvision Ventures as a Technical Engineer (working in the field of Climate Risk Modelling and Monitoring)",
      interests: ["Data Science", "WRF model", "Climate Risk Modelling and Monitoring","RS and GIS", "AI/ML application in Agriculture"],
      publications: [],
      google_scholar: "https://scholar.google.com/citations?user=36qF2IcAAAAJ&hl=en",
      researchgate: "https://www.researchgate.net/profile/Bikash-Behera-8?ev=hdr_xprf",
      linkedin: "https://www.linkedin.com/in/bikash4044/",
      website: "",
    },
    {
      id: "Nida",
      name: "Nida Fathima",
      role: "Alumni",
      category: "Alumni",
      research: "Design of Drippers, Computational fluid dynamics modelling",
      photo: "images/Nida.jpeg",
      initials: "NF",
      color: "#5a8b1a",
      email: "",
      phone: "",
      joining_year: "2023-2025",
      hometown: "Kerala, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2025)",
        "B.Tech, Agricultural Engineering, Kelappaji College of Agrl. Engineering & Technology, Tavanur, India, (2023)",
      ],
      bio: "Nida is currently working as Junior Research Fellow at National Institute of Technology Calicut",
      interests: ["Design of Drippers", "Computational fluid dynamics modelling","RS and GIS"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/nida-fathima79/",
      website: "",
    },
    {
      id: "Chitta",
      name: "Chitranjan",
      role: "Alumni",
      category: "Alumni",
      research: "Climate modelling",
      photo: "images/Chitta.jpeg",
      initials: "CH",
      color: "#5a8b1a",
      email: "",
      phone: "",
      joining_year: "2023-2025",
      hometown: "Orissa, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2025)",
        "B.Tech, Agricultural Engineering, Kelappaji College of Agrl. Engineering & Technology, Tavanur, India, (2023)",
      ],
      bio: "",
      interests: ["Climate modelling","RS and GIS"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "",
      website: "",
    },
    {
      id: "Babji-1",
      name: "Babji",
      role: "M.Tech",
      category: "Master Students",
      research: "Climate Modeling, Land Surface",
      photo: "images/Babji.jpg",
      initials: "AR",
      color: "#5a8b1a",
      email: "",
      phone: "",
      joining_year: "2024",
      hometown: "Telangana, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2026)",
        "B.Tech, Agricultural Engineering, College of agricultural engineering madakasira,Andhra Pradesh, India (2024)",
      ],
      bio: "Babji works on climate modelling and land surface processes, studying how land use changes and surface energy fluxes influence regional climate patterns over the Indian subcontinent. He is also involved in the lab's agro-informatics and Python training activities.",
      interests: ["Climate Modeling", "Land Surface Processes", "WRF Model", "Surface Energy Balance", "Regional Climate"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/babji-sh-742b0126a/",
      website: "",
    },
    {
      id: "Jayant1",
      name: "Jayant Chand",
      role: "M.Tech",
      category: "Master Students",
      research: "Crop monitoring, AL/ML",
      photo: "images/Jayant.jpeg",
      initials: "Jy",
      color: "#5a8b1a",
      email: "",
      phone: "",
      joining_year: "2024",
      hometown: "Jharakhand, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2026)",
        "B.Tech,Agricultural Engineering, Birsa Agricultural University (BAU), Ranchi, India (2023)",
      ],
      bio: "Jaynat is currently a member of Vassar Labs.",
      interests: ["Crop monitoring", "AL/ML", "Vision Language Model", "RS and GIS"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/jayant-chand-b03452255/",
      website: "",
    },
    {
      id: "Bibaswan",
      name: "Bibaswan Bhattacharya",
      role: "M.Tech",
      category: "Master Students",
      research: "Climate Modelling, WRF",
      photo: "images/Bibaswan.jpeg",
      initials: "BB",
      color: "#5a8b1a",
      email: "",
      phone: "",
      joining_year: "2024",
      hometown: "West Bengal, India",
      education: [
        "M.Tech, IIT Kharagpur, India (2026)",
        "B.Tech,Agricultural Engineering, Uttar Banga Krishi Vishwavidyalaya, Cooch Behar, India (2024)",
      ],
      bio: "",
      interests: ["Climate Modelling", "WRF", "Atmospheric Science", "RS and GIS"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/bibaswan14/",
      website: "",
    },
    {
      id: "Ankit",
      name: "Ankit Kumar",
      role: "M.Tech",
      category: "Master Students",
      research: "Climate Modelling, WRF",
      photo: "images/Ankit.jpeg",
      initials: "AK",
      color: "#5a8b1a",
      email: "",
      phone: "",
      joining_year: "2025",
      hometown: "Bihar, India",
      education: [
        "M.Tech, IIT Kharagpur, India (Ongoing)",
        "B.Tech, Agricultural Engineering, Anand Agricultural University, Anand, Gujarat, India (2025)",
      ],
      bio: "",
      interests: ["Climate Modelling", "WRF", "RS and GIS"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/ankit-kumar-9b3b06228/",
      website: "",
    },
    {
      id: "Aryan",
      name: "Aryan Patidar",
      role: "M.Tech",
      category: "Master Students",
      research: "Crop monitoring, Crop Phenology",
      photo: "images/Aryan.jpeg",
      initials: "AP",
      color: "#5a8b1a",
      email: "",
      phone: "",
      joining_year: "2025",
      hometown: "Madhya Pradesh, India",
      education: [
        "M.Tech, IIT Kharagpur, India (Ongoing)",
        "B.Tech, Agricultural Engineering, Indhira Gandhi Krishi Vishwavidyalaya, Raipur, India (2025)",
      ],
      bio: "",
      interests: ["Crop monitoring", "Crop Phenology", "RS and GIS"],
      publications: [],
      google_scholar: "",
      researchgate: "",
      linkedin: "https://www.linkedin.com/in/aryan-patidar-720b70371/",
      website: "",
    }
  ],

  gallery: [
    { src: "images/lab1.jpg", caption: "Lab fieldwork — monsoon field campaign" },
    { src: "images/lab2.jpg", caption: "Annual lab retreat — IIT KGP campus" },
    { src: "images/lab3.jpg", caption: "AGU Fall Meeting 2024 — San Francisco" },
    { src: "images/lab4.jpg", caption: "EGU General Assembly 2025 — Vienna" },
    { src: "images/lab5.jpg", caption: "Agro-Informatics Workshop — IIT Kharagpur 2024" },
    { src: "images/lab6.jpg", caption: "Research group photo — 2024" },
  ],

  news: [
    {
      date: "Recently 2026",
      text: "Ranjan Kumar, Amey Pathak & Kulkarni Shashikanth have published a research article: <strong>Climatic and transient controls on Indian monsoon E-P variability using moisture-budget decomposition.</strong>",
      link: "https://iopscience.iop.org/article/10.1088/2515-7620/ae73ee/meta",
      linkText: "Read Article"
    },
    {
      date: "Recently 2026",
      text: "Ranjeet Singh Bais & Amey Pathak have published a research article: <strong>Extreme learning machine based sub-seasonal forecasting of Indian Monsoon rainfall over core monsoon zone.<strong>",
      link: "https://link.springer.com/article/10.1007/s00704-026-06274-z",
      linkText: "Read Article"
    },
    {
      date: "Early 2025",
      text: "Prof. Pathak's lab is recruiting! Postdoc position available under ANRF National Postdoc Fellowship in hydroclimate/AI-ML.",
      link: "https://www.linkedin.com/feed/update/urn:li:activity:7423281799621132288/",
      linkText: "Read Article"
    }
  ],

  activities: [
    {
      title: "EGU General Assembly 2026",
      date: "2026",
      role: "Presenter",
      description: "We have presented two works at EGU General Assembly 2026 with the titles - Assessment of droughts and extremes over India using CMIP6 simulations (Author: Amey Pathak, Shashikanth Kulkarni, Kaustubh Salvi, Hima Saji, Harish Gupta, Banoth Tejaswi) and Evaluating SAM3 and Conventional Image Processing Method for Potato Canopy Cover Estimation as an Indicator of Crop Health (Author: Alok Kumar Maurya and Amey Pathak).",
      images: ["images/activities/egu261.jpeg", "images/activities/egu262.jpeg"]
    },
    {
      title: "Agro-Informatics Workshop",
      date: "2024",
      role: "Organizer",
      description: "Organized the Advanced ESDP Training Program on Agro-Informatics at IIT Kharagpur funded by MSME, Govt. of India.",
      images: ["images/activities/workshop1.jpg", "images/activities/workshop2.jpg", "images/activities/workshop3.jpg"]
    },
    {
      title: "Field Spectral Campaign",
      date: "2025",
      role: "Research Volunteer",
      description: "Conducted field hyperspectral measurements for crop stress monitoring.",
      images: ["images/activities/field1.jpg", "images/activities/field2.jpg"]
    }
  ],

  contact: {
    address: "Agricultural & Food Engineering Department\nIIT Kharagpur, Kharagpur — 721302\nWest Bengal, India",
    email_pi: "amey[at]agfe[dot]iitkgp[dot]ac[dot]in",
    email_lab: "hydroclimatelab[at]gmail[dot]com",
    phone: "+91-3222-283XXX",
    office_hours: "Monday – Friday: 10:00 AM – 5:00 PM IST",
    google_maps: "https://maps.google.com/?q=IIT+Kharagpur",
    google_form: "https://docs.google.com/forms/d/e/1FAIpQLScvhJjdQ4rVCPiBvqMp5JIIF1_-kd3RFOr-WjErgejeMPJFZw/viewform?usp=dialog",
  }
};
