// Auto-generated publications data
const publicationsData = {
  journals: [
    {
      "authors": "Maurya, Alok Kumar, Behera, Bikash Ranjan, Pathak, Amey",
      "title": "IoT-enabled YOLO-based Real-time Weed Infestation Detection and Alert System for Potato Crop Management",
      "publication": "Potato Research (European Association for Potato Research)",
      "volume": "132",
      "number": "69:132",
      "pages": "1-30",
      "year": "2026",
      "publisher": "Springer Nature, https://doi.org/10.1007/s11540-026-10087-y",
      "type": "Journal",
      "doi": "https://doi.org/10.1007/s11540-026-10087-y"
    },
    {
      "authors": "Bais, Ranjeet Singh, Pathak, Amey",
      "title": "Extreme learning machine based sub-seasonal forecasting of Indian Monsoon rainfall over core monsoon zone",
      "publication": "Theoretical and Applied Climatology",
      "volume": "157",
      "number": "325",
      "pages": "325",
      "year": "2026",
      "publisher": "Springer Nature; https://doi.org/10.1007/s00704-026-06274-z",
      "type": "Journal",
      "doi": "10.1007/s00704-026-06274-z"
    },
    {
      "authors": "Kumar, Ranjan, Pathak, Amey, Shashikanth, Kulkarni",
      "title": "Climatic and transient controls on Indian monsoon E-P variability using moisture-budget decomposition",
      "publication": "Environmental Research Communications",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2026",
      "publisher": "IOP Science, https://doi.org/10.1088/2515-7620/ae73ee",
      "type": "Journal",
      "doi": "10.1088/2515-7620/ae73ee"
    },
    {
      "authors": "Kumar, Ranjan, Pathak, Amey",
      "title": "Lagrangian quantification of atmospheric moisture sources for extreme rainfall events over India during the 2023 summer monsoon",
      "publication": "Science of the Total Environment https://doi.org/10.1016/j.scitotenv.2025.180389",
      "volume": "1000",
      "number": "",
      "pages": "180389",
      "year": "2025",
      "publisher": "Elsevier, https://doi.org/10.1016/j.scitotenv.2025.180389",
      "type": "Journal",
      "doi": "10.1016/j.scitotenv.2025.180389"
    },
    {
      "authors": "Maurya, Alok kumar, Pathak, Amey",
      "title": "Leveraging the use of digital agriculture and machine learning for accurate prediction of Leaf Area Index (LAI)",
      "publication": "Computers and Electronics in Agriculture",
      "volume": "239",
      "number": "110947, ISSN 0168-1699",
      "pages": "",
      "year": "2025",
      "publisher": "Elsevier, https://doi.org/10.1016/j.compag.2025.110947",
      "type": "Journal",
      "doi": "10.1016/j.compag.2025.110947"
    },

    {
      "authors": "Kumar, Ranjan, Pathak, Amey",
      "title": "On Origins and Sustenance of Monsoon Extreme Rainfall During the Year 2023 Over India",
      "publication": "Available at SSRN 4976231",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2023",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Das, Kousik, Sarkar, Soumyajit, Mukherjee, Abhijit, Das, Prerona, Pathak, Amey",
      "title": "Observing tidal and storm generated wave height impact on groundwater levels in a tropical delta (the Sundarbans)",
      "publication": "Journal of Hydrology",
      "volume": "603",
      "number": "",
      "pages": "126813",
      "year": "2021",
      "publisher": "Elsevier",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Hari, Vittal, Pathak, Amey, Koppa, Aakash",
      "title": "Dual response of Arabian Sea cyclones and strength of Indian monsoon to Southern Atlantic Ocean",
      "publication": "Climate Dynamics",
      "volume": "",
      "number": "",
      "pages": "https://link.springer.com/article/10.100",
      "year": "2020",
      "publisher": "Springer",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Pathak, Amey, Ghosh, Subimal",
      "title": "Land\u2013Atmosphere Interactions in Indian Monsoon at Sub-seasonal to Seasonal Scale",
      "publication": "Hydrology in a Changing World:",
      "volume": "",
      "number": "",
      "pages": "139-152",
      "year": "2019",
      "publisher": "Springer Water",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Sahana, AS, Pathak, Amey, Roxy, MK, Ghosh, Subimal",
      "title": "Understanding the role of moisture transport on the dry bias in Indian monsoon simulations by CFSv2",
      "publication": "Climate Dynamics",
      "volume": "52",
      "number": "1",
      "pages": "637-651",
      "year": "2019",
      "publisher": "Springer",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Venkataraman, Chandra, Mishra, Trupti, Ghosh, Subimal, Karmakar, Subhankar",
      "title": "Climate Change Signals and Response: A Strategic Knowledge Compendium for India",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2019",
      "publisher": "Springer",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Sahana AS, Amey Pathak, M.K. Roxy, Subimal Ghosh",
      "title": "Understanding the role of moisture transport on the dry bias in indian monsoon simulations by CFSv2",
      "publication": "Climate Dynamics",
      "volume": "",
      "number": "https ://doi.org/10.1007/s0038 2-018-41",
      "pages": "",
      "year": "2018",
      "publisher": "Springer-Verlag GmbH Germany",
      "type": "Journal",
      "doi": "10.1007/s0038"
    },
    {
      "authors": "Pathak, Amey, Paul, Supantha, Ghosh, Subimal",
      "title": "Land-surface feedback and impacts of land-use change to Indian monsoon rainfall",
      "publication": "Climate Change Signals and Response: A Strategic Knowledge Compendium for India",
      "volume": "",
      "number": "",
      "pages": "3-20",
      "year": "2018",
      "publisher": "Springer Singapore Singapore",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Joseph, Jisha, Ghosh, Subimal, Pathak, Amey, Sahai, AK",
      "title": "Hydrologic impacts of climate change: Comparisons between hydrological parameter uncertainty and climate model uncertainty",
      "publication": "Journal of Hydrology",
      "volume": "566",
      "number": "",
      "pages": "1-22",
      "year": "2018",
      "publisher": "Elsevier",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Jisha Joseph, Jisha Joseph, Subimal Ghosh, Subimal Ghosh, Amey Pathak, Amey Pathak, Sahai, AK",
      "title": "Hydrologic impacts of climate change: comparisons between hydrological parameter uncertainty and climate model uncertainty.",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2018",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Pathak, Amey, Ghosh, Subimal, Martinez, J Alejandro, Dominguez, Francina, Kumar, Praveen",
      "title": "Role of Oceanic and Land Moisture Sources and Transport in the Seasonal and Inter-annual variability of Summer Monsoon in India",
      "publication": "Journal of Climate",
      "volume": "30",
      "number": "",
      "pages": "1839-1859",
      "year": "2017",
      "publisher": "American Meteorological Society",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Barik, Beas, Ghosh, Subimal, Sahana, A Saheer, Pathak, Amey, Sekhar, Muddu",
      "title": "Water Food Energy Nexus: Changing Scenarios in India during recent Decades",
      "publication": "Hydrology and Earth System Science",
      "volume": "21",
      "number": "",
      "pages": "3042-3060",
      "year": "2017",
      "publisher": "Copernicus Publications on behalf of the European Geosciences Union",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Roxy, Koll, Ghosh, Subimal., Pathak, Amey, Athulya R., Mujumdar, M., Murtugudde, Raghu., Terray, P., Krishnan, R., Rajeevan, M",
      "title": "A threefold rise in widespread extreme rain events over central India",
      "publication": "Nature Communications",
      "volume": "8",
      "number": "708",
      "pages": "",
      "year": "2017",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Pathak Amey, Ghosh Subimal, Raghu Murtugudde, and Praveen Kumar",
      "title": "Role of Oceanic and Terrestrial Atmospheric Moisture Sources in Intraseasonal Variability of Indian Summer Monsoon Rainfall",
      "publication": "Scientific Reports",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2017",
      "publisher": "Springer",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Amey Pathak, Amey Pathak, Subimal Ghosh, Subimal Ghosh, Martinez, JA, Dominguez, F, Praveen Kumar, Praveen Kumar",
      "title": "Role of oceanic and land moisture sources and transport in the seasonal and interannual variability of summer monsoon in India.",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2017",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Beas Barik, Beas Barik, Subimal Ghosh, Subimal Ghosh, Sahana, AS, Amey Pathak, Amey Pathak, Muddu Sekhar, Muddu Sekhar",
      "title": "Water-food-energy nexus with changing agricultural scenarios in India during recent decades.",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2017",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Amey Pathak, & Subimal Ghosh, Dawn Emil Sebastian",
      "title": "Use of Atmospheric Budget to Reduce Uncertainty in Estimated Water Availability over South Asia from Different Reanalyses",
      "publication": "Scientific Reports",
      "volume": "6",
      "number": "Article number: 29664 (2016)",
      "pages": "doi:10.1038/srep29664",
      "year": "2016",
      "publisher": "",
      "type": "Journal",
      "doi": "10.1038/srep29664"
    },
    {
      "authors": "Vittal, H, Ghosh, Subimal, Karmakar, Subhankar, Pathak, Amey, Murtugudde, Raghu",
      "title": "Lack of dependence of Indian summer monsoon rainfall extremes on temperature: an observational evidence",
      "publication": "Scientific Reports",
      "volume": "6",
      "number": "1",
      "pages": "31039",
      "year": "2016",
      "publisher": "Nature Publishing Group UK London",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Subimal Ghosh, Robert Oglesby, Amey Pathak, Anita Chandrasekharan, RAAJ Ramsankaran, Supantha Paul",
      "title": "Weakening of Indian Summer Monsoon Rainfall due to Changes in Land Use Land Cover",
      "publication": "Scientific Reports",
      "volume": "6",
      "number": "32177",
      "pages": "",
      "year": "2016",
      "publisher": "Nature",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Vittal, H, Ghosh, S, Karmakar, S, Pathak, A, Murtugudde, R",
      "title": "Lack of Dependence of Indian summer monsoon rainfall extremes on temperature: an observational evidence. Sci Rep 6: 31039",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2016",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Paul, S, Ghosh, S, Oglesby, R, Pathak, A, Chandrasekharan, A, Ramsankaran, RAAJ",
      "title": "Weakening of Indian summer monsoon rainfall due to changes in land use land cover. Sci Rep 6: 32177",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2016",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Supantha Paul, Supantha Paul, Subimal Ghosh, Subimal Ghosh, Oglesby, R, Amey Pathak, Amey Pathak, Anita Chandrasekharan, Anita Chandrasekharan, Ramsankaran, RAAJ",
      "title": "Weakening of Indian summer monsoon rainfall due to changes in land use land cover.",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2016",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Amey Pathak, A.S. Sahana, Subimal Ghosh",
      "title": "Impact of Atmospheric Moisture Transport on Indian Summer Monsoon Onset and Withdrawal",
      "publication": "Dynamics of the Indian Ocean: perspective and Retrospective",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2015",
      "publisher": "National Institute of Oceanography, Goa, India",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Pathak, Banga, Ghosh, Subimal, Kumar, Praveen",
      "title": "Precipitation recycling in the Indian subcontinent during summer monsoon",
      "publication": "Journal of Hydrometeorology",
      "volume": "15",
      "number": "5",
      "pages": "2050-2066",
      "year": "2014",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Amey Pathak, Amey Pathak, Subimal Ghosh, Subimal Ghosh, Kumar, P",
      "title": "Precipitation recycling in the Indian subcontinent during summer monsoon.",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2014",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    }
  ],
  conferences: [
    {
      "authors": "Bais, Ranjeet Singh, Pathak, Amey",
      "title": "Impact of Land Initialization using Target codes for Subseasonal forecasting",
      "publication": "106th AMS Annual Meeting",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2026",
      "publisher": "AMS",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, Amey, Kulkarni, Shashikanth, Salvi, Kaustubh, Saji, Hima, Gupta, Harish, Tejaswi, Banoth",
      "title": "Assessment of droughts and extremes over India using CMIP6 simulations",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2026",
      "publisher": "Copernicus Meetings",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Maurya, Alok Kumar, Pathak, Amey",
      "title": "Evaluating SAM3 and Conventional Image Processing Method for Potato Canopy Cover Estimation as an Indicator of Crop Health",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2026",
      "publisher": "Copernicus Meetings",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Kumar, Ranjan, Pathak, Amey",
      "title": "Tracing Moisture Flow from the Bay of Bengal and Arabian Sea with its Impact on Ganga Basin during Monsoonal Extremes",
      "publication": "EGU General Assembly Conference Abstracts",
      "volume": "",
      "number": "",
      "pages": "EGU25-4531",
      "year": "2025",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, Amey, Behera, Bikash Ranjan, Shashikanth, Kulkarni",
      "title": "ASSESSING FUTURE CONSECUTIVE DRY AND WET DAYS IN CENTRAL INDIA: A CMIP6 DOWNSCALING APPROACH",
      "publication": "AGU25",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2025",
      "publisher": "AGU",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Maurya, Alok Kumar, Pathak, Amey",
      "title": "Effects of Water Stress on Spectral Reflectance of Potato Crop Grown in Open Field Conditions",
      "publication": "European Geosciences Union General Assembly 2024 (EGU24)",
      "volume": "",
      "number": "",
      "pages": "4383",
      "year": "2024",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, Amey, Raj, Ark, Shashikanth, Kulkarni",
      "title": "Statistical Downscaling of CMIP6 based Monsoon Rainfall over India and its Assessment",
      "publication": "AGU24",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2024",
      "publisher": "AGU",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Kumar, Ranjan, Chouhan, Pramod, Pathak, Amey",
      "title": "Identification of Atmospheric Rivers Linked to Extreme Precipitation in the Core Monsoon Zone of India",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2024",
      "number": "",
      "pages": "A07-03",
      "year": "2024",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Kumar, Ranjan, Pathak, Amey",
      "title": "Role of Western Indian Ocean on the Indian Monsoon Extreme Events during 2023",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2024",
      "number": "",
      "pages": "A43Y-03",
      "year": "2024",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Maurya, Alok Kumar, Pathak, Amey, Tiwari, KN, Machavaram, Rajendra",
      "title": "Canopy Cover Monitoring for the Potato Crop under Different Nitrogen Treatment",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2024",
      "number": "",
      "pages": "B01-43",
      "year": "2024",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Maurya, Alok Kumar, Pathak, Amey",
      "title": "Spectral Response of Potato Crop under Different Water-stress Conditions",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2023",
      "number": "",
      "pages": "GC06-11",
      "year": "2023",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Kumar, Ranjan, Pathak, Amey",
      "title": "Diagnostic Evaluation of Atmospheric Moisture Budget (EP) during ENSO years and its relation to ISM rainfall variability.",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2022",
      "number": "",
      "pages": "H44C-07",
      "year": "2022",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Chug, Divyansh, Pathak, Amey, Indu, J., Jain, Sharad, K., Jain Sanjay, K., Dimri, A. P., Niyogi, Dev, Ghosh, Subimal",
      "title": "Observed Evidence for Steep Rise in the Extreme Flow of Western Himalayan Rivers",
      "publication": "Geophysical Research Letters",
      "volume": "",
      "number": "doi: 10.1029/2020GL087815",
      "pages": "",
      "year": "2020",
      "publisher": "American Geophysical Union",
      "type": "Conference",
      "doi": "10.1029/2020GL087815"
    },
    {
      "authors": "Dubey, Nivedita, Pathak, Amey",
      "title": "Evaluation of CMIP6 Models' Performance on Simulation of Indian Summer Monsoon",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2019",
      "number": "",
      "pages": "GC42E-07",
      "year": "2019",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, Amey, Salvi, Kaustubh Anil",
      "title": "Glimpse of Indian Summer Monsoon Ranfall Through CMIP6 Decadal Hindcast: AN Assessment Study",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2019",
      "number": "",
      "pages": "GC33E-1450",
      "year": "2019",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, Amey, Salvi, Kaustubh Anil",
      "title": "Credibility of CMIP5 Decadal Predictions to Comprehend the Intraseasonal Variability of the Indian Monsoon",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2018",
      "number": "",
      "pages": "A11N-2457",
      "year": "2018",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Salvi, Kaustubh Anil, Pathak, Amey",
      "title": "Fidelity Assessment of Decadal Temperature Predictions in Capturing Heat Waves over India",
      "publication": "AGU Fall Meeting 2018",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2018",
      "publisher": "AGU",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, A, Salvi, KA",
      "title": "Fidelity Assessment of Decadal Temperature Predictions in Capturing Heat Waves over India",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2018",
      "number": "",
      "pages": "GH22A-06",
      "year": "2018",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Ghosh, Subimal, Shastri, Hiteshri, Pathak, Amey, Paul, Supantha",
      "title": "Changing pattern of Indian monsoon extremes: global and local factors",
      "publication": "EGU General Assembly Conference Abstracts",
      "volume": "",
      "number": "",
      "pages": "2392",
      "year": "2017",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Barik, Beas, Ghosh, Subimal, Pathak, Amey",
      "title": "Changes in Water-Food-Energy Nexus in India and its consistency with changes in Monsoon",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2017",
      "number": "",
      "pages": "H42A-01",
      "year": "2017",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Sahana Saheer, Amey Pathak, Subimal Ghosh, Beas Barik",
      "title": "Evaluating Ground Water Storage towards Sustainable Water-Food-Energy Management",
      "publication": "European Geophysical Union",
      "volume": "",
      "number": "EGU2016-996",
      "pages": "996",
      "year": "2016",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Amey Pathak, Roxy Mathew Koll, Subimal Ghosh, Sahana Saheer",
      "title": "Understanding Dry Bias in the Simulations of Indian Monsoon by CFSv2 Through Analysis of Moisture",
      "publication": "European Geophysical Union",
      "volume": "",
      "number": "EGU2016",
      "pages": "7346",
      "year": "2016",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Saheer, Sahana, Pathak, Amey, Mathew, Roxy, Ghosh, Subimal",
      "title": "Understanding Dry Bias in the Simulations of Indian Monsoon by CFSv2 Through Analysis of Moisture Transport",
      "publication": "EGU General Assembly Conference Abstracts",
      "volume": "",
      "number": "",
      "pages": "EPSC2016-7346",
      "year": "2016",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Barik, Beas, Saheer, Sahana, Pathak, Amey, Ghosh, Subimal",
      "title": "Evaluating Ground Water Storage towards Sustainable Water-Food-Energy Management",
      "publication": "EGU General Assembly Conference Abstracts",
      "volume": "",
      "number": "",
      "pages": "EPSC2016-996",
      "year": "2016",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, Amey, Ghosh, Subimal",
      "title": "Impact of Atmospheric Moisture Transport on Interannual and Intraseasonal Variations of the Indian Summer Monsoon",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2016",
      "number": "",
      "pages": "A13F-0353",
      "year": "2016",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Joseph, Jisha, Pathak, Amey, Ghosh, Subimal",
      "title": "Uncertainty assessment in climate change simulation of Ganges basin",
      "publication": "EGU General Assembly Conference Abstracts",
      "volume": "",
      "number": "",
      "pages": "537",
      "year": "2015",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Sebastian, Dawn, Pathak, Amey, Ghosh, Subimal",
      "title": "Understanding Moisture and Energy Budget for South Asian Monsoon",
      "publication": "EGU General Assembly Conference Abstracts",
      "volume": "",
      "number": "",
      "pages": "538",
      "year": "2015",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Amey Pathak, Hiteshri Shastri, Subimal Ghosh",
      "title": "Feedback from Urbanization and Land Surface ET to Indian Summer Monsoon Rainfall,",
      "publication": "National Climate Science Conference",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2015",
      "publisher": "Centre for Climate Change, Indian Institute of Science, Bangalore",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Dawn Sebastian, Amey Pathak, Subimal Ghosh",
      "title": "Improving the Consistency in Water Availability between Different Reanalysis Data over South Asia",
      "publication": "American Geophysical Union Fall Meeting",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2015",
      "publisher": "American Geophysical Union",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Jisha Joseph, Amey Pathak, Subimal Ghosh",
      "title": "Uncertainty assessment in climate change simulation of Ganges basin",
      "publication": "American Geophysical Union Fall Meeting",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2015",
      "publisher": "American Geophysical Union",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Amey Pathak, A.S. Sahana, Subimal Ghosh",
      "title": "Role of Terrestrial Moisture Source Transport on Summer Monsoon Rainfall Variability over Ganga River Basin",
      "publication": "American Geophysical Union Fall Meeting",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2015",
      "publisher": "American Geophysical Union Fall Meeting",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, A, Ghosh, S, Kumar, P",
      "title": "Role of Terrestrial Moisture Source Transport on Summer Monsoon Rainfall Variability over Ganga River Basin",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2015",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Joseph, J, Sebastian, DE, Pathak, A, Ghosh, S",
      "title": "Improving the Consistency in Water Availability between Different Reanalysis Data over South Asia",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2015",
      "number": "",
      "pages": "H41A-1272",
      "year": "2015",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "AS, S, Pathak, A, Ghosh, S, Kumar, P",
      "title": "Role of Terrestrial Moisture Source Transport on Summer Monsoon Rainfall Variability over Ganga River Basin",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2015",
      "number": "A33J-0324",
      "year": "2015",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Sebastian, Dawn EMIL, Pathak, Amey, Ghosh, Subimal, Joseph, Jisha",
      "title": "Improving the Consistency in Water Availability between Different Reanalysis Data over South Asia",
      "publication": "2015 AGU Fall Meeting",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2015",
      "publisher": "AGU",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, Amey, Ghosh, Subimal, Kumar, Praveen",
      "title": "Precipitation recycling in the Indian subcontinent during summer monsoon",
      "publication": "Journal of Hydrometeorology",
      "volume": "15",
      "number": "5",
      "pages": "2050-2066",
      "year": "2014",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Amey Pathak, Amey Pathak, Subimal Ghosh, Subimal Ghosh, Kumar, P",
      "title": "Precipitation recycling in the Indian subcontinent during summer monsoon.",
      "publication": "Unknown",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2014",
      "publisher": "",
      "type": "Journal",
      "doi": ""
    },
    {
      "authors": "Amey Pathak, Subimal Ghosh, Praveen Kumar",
      "title": "Precipitation Recycling in India during South West Monsoon",
      "publication": "American Geophysical Union Fall Meeting",
      "volume": "",
      "number": "",
      "pages": "",
      "year": "2012",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    },
    {
      "authors": "Pathak, A, Ghosh, S, Kumar, P",
      "title": "Precipitation Recycling in India during South West Monsoon",
      "publication": "AGU Fall Meeting Abstracts",
      "volume": "2012",
      "number": "H51C-1351",
      "year": "2012",
      "publisher": "",
      "type": "Conference",
      "doi": ""
    }
  ],
  all: []
};



publicationsData.all = [
  ...publicationsData.journals,
  ...publicationsData.conferences
];

if (typeof LAB_DATA !== "undefined") {
    LAB_DATA.publications = publicationsData.all.map(p => ({
        year: p.year,
        title: p.title,
        authors: p.authors,
        journal: p.publication || "Proceeding / Presentation",
        volume: p.volume || "",
        pages: p.pages || "",
        scholar: p.doi ? `https://doi.org/${p.doi}` : "#"
    }));
}

const publicationStats = {
    totalJournals: publicationsData.journals.length,
    totalConferences: publicationsData.conferences.length,
    totalPublications: publicationsData.all.length
};
